"""Écrit src/maps/<id>.ts à partir des brouillons ASCII (tools/maps/draw_maps.py) et des en-têtes
(légendes, zones, lumière) ci-dessous.

Usage : python3 tools/maps/export_ts.py <dossier_brouillons> src/maps
"""
import os
import sys

HEAD = {
    'camp': """{
  id: 'camp',
  name: 'Le camp',
  palette: 'summer',
  base: '.',
  wall: 'none',
  light: { darkness: 0.12, color: [60, 40, 20] },
  viewTiles: 11,
  music: 'music_camp',
  trees: ['world:tree_oak_a', 'world:tree_oak_b', 'world:tree_pine_a', 'world:tree_pine_b'],
  deadTrees: ['world:tree_dead'],
  legend: {
    H: { kind: 'house' },
    X: { kind: 'door', to: 'house', ground: ',' },
    F: { kind: 'building', type: 'campfire', ground: ',' },
    W: { kind: 'building', type: 'workbench', ground: ',' },
    C: { kind: 'building', type: 'chest' },
    A: { kind: 'rack' },
    D: { kind: 'building', type: 'dummy' },
    S: { kind: 'travel' },
    Y: { kind: 'reserved', name: 'Emplacement réservé (futur compagnon)' },
    P: { kind: 'start' },
  },
  areas: [
    { name: 'Le camp', x: 0, y: 0, w: 40, h: 30 },
  ],""",
    'house': """{
  id: 'house',
  name: 'La maison',
  palette: 'summer',
  base: '_',
  wall: 'brick',
  light: { darkness: 0.28, color: [40, 20, 10] },
  viewTiles: 8.5,
  music: 'music_camp',
  trees: [],
  deadTrees: [],
  legend: {
    X: { kind: 'door', to: 'camp', ground: '_' },
    P: { kind: 'start' },
    B: { kind: 'building', type: 'bed' },
    H: { kind: 'building', type: 'hearth' },
    C: { kind: 'building', type: 'chest' },
  },
  areas: [
    { name: 'La maison', x: 0, y: 0, w: 12, h: 9 },
  ],""",
    'bois': """{
  id: 'bois',
  name: 'Bois des chasseurs',
  palette: 'summer',
  base: '.',
  wall: 'cliff',
  light: { darkness: 0.0, color: [0, 0, 0] },
  viewTiles: 11.5,
  music: 'music_day',
  trees: ['world:tree_oak_a', 'world:tree_oak_b', 'world:tree_pine_a', 'world:tree_pine_b', 'world:tree_autumn_a'],
  deadTrees: ['world:tree_dead'],
  legend: {
    E: { kind: 'exit' },
    P: { kind: 'start' },
    J: { kind: 'checkpoint', id: 'bois_lisiere', name: 'Halte de la lisière' },
    K: { kind: 'checkpoint', id: 'bois_pavillon', name: 'Feu du pavillon', ground: ',' },
    L: { kind: 'lodge', sprite: 'world:house_c', w: 5, h: 2, name: 'Pavillon de chasse' },
    N: { kind: 'note', id: 'n_bois_pavillon', ground: ',' },
    Q: { kind: 'note', id: 'n_bois_braconnier' },
    C: { kind: 'chest', id: 'bois_pavillon', loot: 'bois_lodge', renew: true, name: 'Coffre du pavillon' },
    U: { kind: 'chest', id: 'bois_etang', loot: 'bois_pond', renew: true, sprite: 'world:crate_b', name: 'Panier de cueillette' },
    V: { kind: 'chest', id: 'bois_braconnier', loot: 'bois_poacher', sprite: 'world:crate_stack', name: 'Cache du braconnier' },
    Z: { kind: 'chest', id: 'bois_reserve', loot: 'bois_reserve', renew: true, sprite: 'world:barrels', name: 'Réserve des chasseurs' },
    M: { kind: 'prop', sprite: 'props:cave_mouth', w: 2, h: 1, name: 'Tanière' },
    B: { kind: 'boss', type: 'predator', id: 'bois_predateur', ground: ',' },
    '1': { kind: 'spawn', group: ['rat', 'rat'] },
    '2': { kind: 'spawn', group: ['wolf', 'wolf'] },
    '3': { kind: 'spawn', group: ['wolf'] },
    '4': { kind: 'spawn', group: ['deer', 'deer'] },
    '5': { kind: 'spawn', group: ['rat'] },
  },
  areas: [
    { name: 'Lisière', x: 2, y: 36, w: 14, h: 11, landmark: true },
    { name: 'Pavillon de chasse', x: 22, y: 14, w: 14, h: 12, landmark: true },
    { name: 'Étang aux saules', x: 4, y: 11, w: 14, h: 13, landmark: true },
    { name: 'Cache du braconnier', x: 2, y: 2, w: 7, h: 7, landmark: true },
    { name: 'Tanière du prédateur', x: 48, y: 0, w: 16, h: 15, landmark: true },
    { name: 'Réserve des chasseurs', x: 43, y: 17, w: 9, h: 8, landmark: true },
    { name: 'Éboulis de l’est', x: 52, y: 17, w: 11, h: 16, landmark: true },
    { name: 'Prairie aux cerfs', x: 46, y: 34, w: 15, h: 11, landmark: true },
  ],""",
    'marais': """{
  id: 'marais',
  name: 'Marais corrompu',
  palette: 'autumn',
  base: '.',
  wall: 'none',
  light: { darkness: 0.62, color: [10, 22, 30] },
  viewTiles: 11.5,
  music: 'music_eerie',
  trees: ['props:tree_twisted', 'props:tree_bare_c', 'props:tree_bare_d', 'world:tree_dead'],
  deadTrees: ['props:tree_bare_a', 'props:tree_bare_b', 'world:tree_dead'],
  legend: {
    E: { kind: 'exit' },
    P: { kind: 'start' },
    J: { kind: 'checkpoint', id: 'marais_passerelle', name: 'Lanterne de la passerelle', votive: true },
    V: { kind: 'checkpoint', id: 'marais_ilot', name: 'Lanterne de l’îlot', votive: true },
    L: { kind: 'lodge', sprite: 'world:house_c', w: 5, h: 2, name: 'Cabane de la guérisseuse' },
    N: { kind: 'note', id: 'n_marais_cabane' },
    O: { kind: 'prop', sprite: 'props:dolmen_d', w: 4, h: 1, solid: true, occluder: true, name: 'Dolmen' },
    I: { kind: 'prop', sprite: 'props:menhir_d', w: 1, h: 1, solid: true, name: 'Menhir' },
    G: { kind: 'prop', sprite: 'props:tree_giant_dead', w: 3, h: 1, solid: true, occluder: true, name: 'Arbre-mort' },
    Z: { kind: 'chest', id: 'marais_chapelle', loot: 'marais_rare', renew: true, sprite: 'world:chest_big_closed', name: 'Coffre de la chapelle' },
    U: { kind: 'chest', id: 'marais_arbre', loot: 'marais_common', renew: true, sprite: 'world:crate_b', name: 'Offrandes de l’arbre-mort' },
    Q: { kind: 'chest', id: 'marais_roseliere', loot: 'marais_hidden', sprite: 'world:crate_stack', name: 'Cache de la roselière' },
    Y: { kind: 'shortcut', id: 'marais_tronc', name: 'Tronc couché', sprite: 'props:bridge_deck', from: 'north', cells: { dx: 0, dy: 1, w: 2, h: 7 } },
    F: { kind: 'spawn', group: ['flower'] },
    '1': { kind: 'spawn', group: ['husk'], asleep: true },
    '2': { kind: 'spawn', group: ['fox_c', 'fox_c'] },
    '3': { kind: 'spawn', group: ['wraith'] },
    '4': { kind: 'spawn', group: ['rat', 'rat'] },
  },
  areas: [
    { name: 'Passerelle', x: 26, y: 38, w: 12, h: 10, landmark: true },
    { name: 'Îlot de la guérisseuse', x: 25, y: 17, w: 14, h: 13, landmark: true },
    { name: 'Roselière', x: 2, y: 7, w: 15, h: 27, landmark: true },
    { name: 'Chapelle engloutie', x: 45, y: 9, w: 15, h: 13, landmark: true },
    { name: 'Arbre-mort', x: 26, y: 2, w: 10, h: 10, landmark: true },
  ],""",
    'bastion': """{
  id: 'bastion',
  name: 'Bastion abandonné',
  palette: 'autumn',
  base: ',',
  wall: 'castle',
  light: { darkness: 0.32, color: [20, 24, 40] },
  viewTiles: 12,
  music: 'music_ruins',
  trees: ['world:tree_autumn_a', 'world:tree_autumn_b', 'world:tree_dead'],
  deadTrees: ['world:tree_dead', 'props:tree_bare_a'],
  legend: {
    E: { kind: 'exit', only: 'main' },
    P: { kind: 'start', only: 'main' },
    '@': { kind: 'start', only: 'dungeon' },
    '&': { kind: 'exit', only: 'dungeon' },
    J: { kind: 'checkpoint', id: 'bastion_porte', name: 'Feu de la porte', only: 'main' },
    Q: { kind: 'checkpoint', id: 'bastion_cour', name: 'Feu de la cour', ground: ':' },
    A: { kind: 'prop', sprite: 'props:arch_gate', w: 4, h: 1, occluder: true, name: 'Porte du bastion' },
    G: { kind: 'gate', id: 'bastion_herse', sprite: 'props:portcullis', w: 1, h: 1, name: 'Herse de la cour', openedBy: 'lever', dungeonOpen: true },
    H: { kind: 'gate', id: 'bastion_ecuries', sprite: 'props:portcullis', w: 1, h: 1, name: 'Herse des écuries', openedBy: 'lever' },
    K: { kind: 'gate', id: 'bastion_poterne', sprite: 'props:portcullis', w: 1, h: 1, name: 'Poterne', openedBy: 'boss', dungeonOpen: true },
    L: { kind: 'lever', id: 'bastion_treuil', opens: 'bastion_herse', name: 'Treuil de la herse', ground: ':' },
    M: { kind: 'lever', id: 'bastion_levier_ecuries', opens: 'bastion_ecuries', name: 'Levier des écuries' },
    C: { kind: 'chest', id: 'bastion_armurerie', loot: 'bastion_armory', ground: ':', name: 'Coffre de l’armurerie', only: 'main' },
    U: { kind: 'chest', id: 'bastion_ecuries', loot: 'bastion_common', name: 'Malle des écuries', only: 'main' },
    Z: { kind: 'chest', id: 'bastion_tresor', loot: 'bastion_boss', sprite: 'world:chest_big_closed', ground: ':', name: 'Trésor du chef' },
    N: { kind: 'note', id: 'n_bastion_chapelle' },
    B: { kind: 'boss', type: 'chief', id: 'bastion_chef', ground: ':' },
    R: { kind: 'prop', sprite: 'props:rocks_pile_d', w: 2, h: 1, solid: true, name: 'Éboulis' },
    O: { kind: 'prop', sprite: 'world:crate_stack', w: 1, h: 1, solid: true },
    W: { kind: 'prop', sprite: 'props:trough', w: 2, h: 1, solid: true, name: 'Abreuvoir', ground: ':' },
    I: { kind: 'prop', sprite: 'world:pillar', w: 1, h: 1, solid: true, occluder: true },
    '1': { kind: 'spawn', group: ['merc', 'merc'], slot: 'a' },
    '2': { kind: 'spawn', group: ['archer'], slot: 'a' },
    '3': { kind: 'spawn', group: ['merc'], slot: 'b', ground: ':' },
    '4': { kind: 'spawn', group: ['merc', 'archer'], slot: 'b', ground: ':' },
    '5': { kind: 'spawn', group: ['husk', 'husk'], slot: 'c' },
    '6': { kind: 'spawn', group: ['archer'], slot: 'boss', ground: ':' },
  },
  areas: [
    { name: 'Porte extérieure', x: 20, y: 44, w: 24, h: 8, landmark: true },
    { name: 'Basse-cour', x: 6, y: 25, w: 52, h: 17, landmark: true },
    { name: 'Caserne incendiée', x: 7, y: 27, w: 13, h: 11, landmark: true },
    { name: 'Écuries', x: 44, y: 27, w: 14, h: 10, landmark: true },
    { name: 'Cour intérieure', x: 6, y: 16, w: 40, h: 6, landmark: true },
    { name: 'Chapelle', x: 46, y: 15, w: 12, h: 7, landmark: true },
    { name: 'Grande salle du donjon', x: 16, y: 2, w: 32, h: 9, landmark: true },
    { name: 'Chemin de ronde', x: 60, y: 14, w: 4, h: 38 },
  ],""",
    'carriere': """{
  id: 'carriere',
  name: 'Ancienne carrière',
  palette: 'summer',
  base: ',',
  wall: 'cliff',
  light: { darkness: 0.28, color: [30, 20, 10], caveDarkness: 0.5 },
  viewTiles: 12,
  music: 'music_ruins',
  trees: ['world:tree_dead', 'props:tree_bare_a'],
  deadTrees: ['world:tree_dead'],
  legend: {
    E: { kind: 'exit', only: 'main' },
    P: { kind: 'start', only: 'main' },
    '@': { kind: 'start', only: 'dungeon' },
    '&': { kind: 'exit', only: 'dungeon' },
    J: { kind: 'checkpoint', id: 'carriere_crete', name: 'Halte de la crête', only: 'main' },
    Q: { kind: 'checkpoint', id: 'carriere_camp', name: 'Feu des carriers', only: 'main' },
    K: { kind: 'checkpoint', id: 'carriere_galeries', name: 'Lanterne des galeries' },
    Y: { kind: 'shortcut', id: 'carriere_echelle', name: 'Échelle relevée', sprite: 'props:ladder', from: 'south', cells: { dx: 0, dy: 0, w: 1, h: 2 } },
    M: { kind: 'prop', sprite: 'props:cave_mouth', w: 2, h: 1, name: 'Entrée des galeries' },
    W: { kind: 'prop', sprite: 'props:table_rough', w: 2, h: 1, solid: true, name: 'Table des carriers' },
    O: { kind: 'prop', sprite: 'world:barrels', w: 2, h: 1, solid: true },
    A: { kind: 'prop', sprite: 'props:rock_tower_s', w: 2, h: 1, solid: true, occluder: true, name: 'Tour de pierres' },
    N: { kind: 'note', id: 'n_carriere_camp' },
    I: { kind: 'prop', sprite: 'props:stalagmite_s', w: 1, h: 1, solid: true },
    C: { kind: 'chest', id: 'carriere_filons', loot: 'carriere_common', name: 'Caisse des filons', sprite: 'world:crate_stack', only: 'main' },
    U: { kind: 'chest', id: 'carriere_fond', loot: 'carriere_common', name: 'Caisse du fond', sprite: 'world:crate_b', only: 'main' },
    V: { kind: 'chest', id: 'carriere_recoin', loot: 'carriere_rare', name: 'Coffre du recoin', only: 'main' },
    Z: { kind: 'chest', id: 'carriere_tresor', loot: 'carriere_boss', sprite: 'world:chest_big_closed', name: 'Nid du ver' },
    B: { kind: 'boss', type: 'worm', id: 'carriere_ver' },
    '1': { kind: 'spawn', group: ['fox_c', 'fox_c'], slot: 'a' },
    '2': { kind: 'spawn', group: ['husk'], asleep: true, slot: 'a' },
    '3': { kind: 'spawn', group: ['bear_c'], slot: 'b' },
    '4': { kind: 'spawn', group: ['wraith'], slot: 'c' },
    '5': { kind: 'spawn', group: ['rat', 'rat'], slot: 'a' },
  },
  areas: [
    { name: 'Crête', x: 1, y: 1, w: 62, h: 12, landmark: true },
    { name: 'Terrasse des carriers', x: 18, y: 15, w: 26, h: 13, landmark: true },
    { name: 'Filons de l’est', x: 48, y: 15, w: 15, h: 13, landmark: true },
    { name: 'Fond de la carrière', x: 1, y: 30, w: 62, h: 8, landmark: true },
    { name: 'Galeries', x: 1, y: 38, w: 62, h: 14, cave: true, landmark: true },
    { name: 'Grande caverne', x: 20, y: 43, w: 26, h: 9, cave: true },
  ],""",
}

if __name__ == '__main__':
    src, out = sys.argv[1], sys.argv[2]
    for k, head in HEAD.items():
        rows = open(os.path.join(src, k + '.txt')).read().rstrip('\n').split('\n')
        body = '\n'.join("    '" + r.replace('\\\\', '\\\\\\\\').replace("'", "\\\\'") + "'," for r in rows)
        const = 'MAP_' + k.upper()
        ts = f"""// Carte « {k} » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type {{ MapDef }} from './types';

export const {const}: MapDef = {head}
  rows: [
{body}
  ],
}};
"""
        with open(os.path.join(out, k + '.ts'), 'w') as fh:
            fh.write(ts)
        print(k, len(rows), 'lignes')
