// Carte « bastion » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_BASTION: MapDef = {
  id: 'bastion',
  name: 'Bastion abandonné',
  palette: 'autumn',
  base: ',',
  wall: 'castle',
  light: { darkness: 0.32, color: [20, 24, 40] },
  viewTiles: 12,
  music: 'music_ruins',
  trees: ['world:tree_autumn_a', 'world:tree_autumn_b', 'world:tree_dead'],
  deadTrees: ['world:tree_dead', 'props:tree_bare_a'],
  legend: {
    E: { kind: 'exit', only: 'main' },
    P: { kind: 'start', only: 'main' },
    '@': { kind: 'start', only: 'dungeon' },
    '&': { kind: 'exit', only: 'dungeon' },
    J: { kind: 'checkpoint', id: 'bastion_porte', name: 'Feu de la porte', only: 'main' },
    Q: { kind: 'checkpoint', id: 'bastion_cour', name: 'Feu de la cour', ground: ':' },
    A: { kind: 'prop', sprite: 'props:arch_gate', w: 4, h: 1, occluder: true, name: 'Porte du bastion' },
    G: { kind: 'gate', id: 'bastion_herse', sprite: 'props:portcullis', w: 1, h: 1, name: 'Herse de la cour', openedBy: 'lever', dungeonOpen: true },
    H: { kind: 'gate', id: 'bastion_ecuries', sprite: 'props:portcullis', w: 1, h: 1, name: 'Herse des écuries', openedBy: 'lever' },
    K: { kind: 'gate', id: 'bastion_poterne', sprite: 'props:portcullis', w: 1, h: 1, name: 'Poterne', openedBy: 'boss', dungeonOpen: true },
    L: { kind: 'lever', id: 'bastion_treuil', opens: 'bastion_herse', name: 'Treuil de la herse', ground: ':' },
    M: { kind: 'lever', id: 'bastion_levier_ecuries', opens: 'bastion_ecuries', name: 'Levier des écuries' },
    C: { kind: 'chest', id: 'bastion_armurerie', loot: 'bastion_armory', ground: ':', name: 'Coffre de l’armurerie', only: 'main' },
    U: { kind: 'chest', id: 'bastion_ecuries', loot: 'bastion_common', name: 'Malle des écuries', only: 'main' },
    Z: { kind: 'chest', id: 'bastion_tresor', loot: 'bastion_boss', sprite: 'world:chest_big_closed', ground: ':', name: 'Trésor du chef' },
    N: { kind: 'note', id: 'n_bastion_chapelle' },
    B: { kind: 'boss', type: 'chief', id: 'bastion_chef', ground: ':' },
    R: { kind: 'prop', sprite: 'props:rocks_pile_d', w: 2, h: 1, solid: true, name: 'Éboulis' },
    O: { kind: 'prop', sprite: 'world:crate_stack', w: 1, h: 1, solid: true },
    W: { kind: 'prop', sprite: 'props:trough', w: 2, h: 1, solid: true, name: 'Abreuvoir', ground: ':' },
    I: { kind: 'prop', sprite: 'world:pillar', w: 1, h: 1, solid: true, occluder: true },
    '1': { kind: 'spawn', group: ['merc', 'merc'], slot: 'a' },
    '2': { kind: 'spawn', group: ['archer'], slot: 'a' },
    '3': { kind: 'spawn', group: ['merc'], slot: 'b', ground: ':' },
    '4': { kind: 'spawn', group: ['merc', 'archer'], slot: 'b', ground: ':' },
    '5': { kind: 'spawn', group: ['husk', 'husk'], slot: 'c' },
    '6': { kind: 'spawn', group: ['archer'], slot: 'boss', ground: ':' },
  },
  areas: [
    { name: 'Porte extérieure', x: 20, y: 44, w: 24, h: 8, landmark: true },
    { name: 'Basse-cour', x: 6, y: 25, w: 52, h: 17, landmark: true },
    { name: 'Caserne incendiée', x: 7, y: 27, w: 13, h: 11, landmark: true },
    { name: 'Écuries', x: 44, y: 27, w: 14, h: 10, landmark: true },
    { name: 'Cour intérieure', x: 6, y: 16, w: 40, h: 6, landmark: true },
    { name: 'Chapelle', x: 46, y: 15, w: 12, h: 7, landmark: true },
    { name: 'Grande salle du donjon', x: 16, y: 2, w: 32, h: 9, landmark: true },
    { name: 'Chemin de ronde', x: 60, y: 14, w: 4, h: 38 },
  ],
  rows: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTT,,,,T,,,,,T################################TTTTT,T,,,,TTTTT',
    'TTT,,,,,,,,,,,,,################################,,,,,,,,,,,,,,TT',
    'TT,,,,,,,,,,,,,,##::::::::::::::::::::::::::::##,,,,,,,,,,,,,,TT',
    'TTT,,,,,,,,,,,,,##::::6:Z:::::::::::::::::6:::##,,,,,,,,,,,,,,TT',
    'TTT,,,,,,,,,,,,,##::::::::::::::B:::::::::::::##,,,,,,,,,,,,,,TT',
    'TT,,,,,,,,,,,,,,##::::::::::::::::::::::::::::##,,,,,,,,,,,,,,TT',
    'TT,,,,,,,,,,,,,,##::::::::::::::::::::::::::::##,,,,,,,,,,,,,TTT',
    'TT,,,,,,,,,,,,,,##############::::##############,,,,,,,,,,,,,,TT',
    'TTT,,,,,,,,,,,,,##############::::##############,,,,,,,,,,,,,TTT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT',
    'TTT,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,,,,,TTT',
    'TT,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,,,,,TTT',
    'TTT,########################################################,,TT',
    'TTT,########################################################,,TT',
    'TTT,##,,,,,,,,,,,,,,,,::::::::::::::::::::,,,,,,,,,,I,,I,,##,,TT',
    'TTT,##,,,,,,,,,,,,,,,,::::::::::::::::::::,,,,,,M,,,,,,,,,##,,TT',
    'TT,,##,,,,#####,,,,,,,::::4::::::W::::::::,,,,,,,,,,N5,,,,,,,,TT',
    'TTTT##,,,,,,,,,,,,,,,,::::::::::::::::::4:,,,,,,,,,,,,,,,,KK,,TT',
    'TTTT##,,,,,,,,,,,,,,,,:::::::Q::::::::::::,,,,4,,,,,I,,I,,##,,TT',
    'TT,,##,,,,,,,,,,,,,,,,::::::::::::::::::::,,,,,,,,,,,,,,,,##,@TT',
    'TTTT###########################,,#################,,########,,TT',
    'TTT,###########################,,#################,,########,&TT',
    'TTT,###########################GG#################HH########,,TT',
    'TTT,##,p,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,##,,TT',
    'TT,,##,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,##,,TT',
    'TT,,##,#############,,Op,,,,,,,,,,,,,,,,,,,,######,,########,,TT',
    'TTT,##,#:L:::::::::#,,,,,,,,,,1,,,,,,,,,O,,,#,,,,,,,,,,,,###,,TT',
    'TT,,##,#:::::::::::#,,,,,,,,,,,,,,#,,,,,,,,,#,,,,,,,,,,U,###,,TT',
    'TT,,##,#:::::::::C:#,,,,R,,,,,,,,,#,,,,,,,2,#,,,,,,,,,,,,###,,TT',
    'TTTT##,#:::::::::::#,,,,,,,,,,,,,,#,,,,,,,,,#,,,,,,,,,,,,###,,TT',
    'TTT,##,#::::3::::::#1,,,####,,,,,,,,,,,,,,,,#,,,,,,,,,,,,###,,TT',
    'TTT,##,#:::::::::::#,,,,,,,,,,,,,,,s,R,,,,,,#,,,,,,,,,,,,###,,TT',
    'TTT,##,#::::::::3::#,,,,,,,,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,###,,TT',
    'TTT,##,#:::::::::::#,,,,,,O,,,,,,,,,,,,,,,,,#,,,,,,,,,,,,###,,TT',
    'TT,T##,#:::::::::::#ss,,,,,,,,,,,,,,1,,,,,,,#####,,,########,,TT',
    'TT,,##,#####,,,#####,,,,,,,,,,,,,,,,,,####,,,,,,,,,,,,,,,,##,,TT',
    'TTT,##,,,,,,,,,,,p,,,,#,,s,,R,,,,,,,,,,,,,,,,p,,,,,s,,,,,,##,,TT',
    'TT,,##,,,,,,,,,,,,,,,,#,,,,,,,,,,,,,,,,,,,O,,,,,,,,,,,,,,,##,,TT',
    'TT,,##,,,,,,,,2,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,##,,TT',
    'TT,,##,,,,,,,,,,,,,,,p,,s,,,,,,,,,,s,,,,,,,,,,,,,,,,,,,,,,##,,TT',
    'TT,,###########################,,###########################,,TT',
    'TTTT###########################,,###########################,,TT',
    'TT,,##########################A,,###########################,,TT',
    'TTT,,,,",,,,,,,,,,,,,,,,,,,,,,,,",,,t,,,,,"t,,,,,,,t,,,,,t,,,,TT',
    'TTT,,,,,t,,,,,,,,t,,,,,t,,t,,,",,,,,,,,,,,,,,,t",,t,,,,,,,,,t,TT',
    'TT,,t,,,,t,,,,,,,,,,,,t,,,,,,,,t,J,,",,",,,,,,,,,,,,,,,,,t,,,,TT',
    'TTT,t,,,,,,,,,,,",,,,,t,,,t,,,,,,,,,,,"t,t,,,,t,,,,,,t,t",,,,,TT',
    'TT,tT,T,TTT,T,,T,,T,TT,,TT,,,T,PTTT,,,T,,,,tt,t,,,,,,,,,,,tt",,T',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTETT,TTTTTTTT,TTTTTTTTTTTTTTTTTTTT,TT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT,,,TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  ],
};
