// Carte « bois » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_BOIS: MapDef = {
  id: 'bois',
  name: 'Bois des chasseurs',
  palette: 'summer',
  base: '.',
  wall: 'cliff',
  light: { darkness: 0.0, color: [0, 0, 0] },
  viewTiles: 11.5,
  music: 'music_day',
  trees: ['world:tree_oak_a', 'world:tree_oak_b', 'world:tree_pine_a', 'world:tree_pine_b', 'world:tree_autumn_a'],
  deadTrees: ['world:tree_dead'],
  legend: {
    E: { kind: 'exit' },
    P: { kind: 'start' },
    J: { kind: 'checkpoint', id: 'bois_lisiere', name: 'Halte de la lisière' },
    K: { kind: 'checkpoint', id: 'bois_pavillon', name: 'Feu du pavillon', ground: ',' },
    L: { kind: 'lodge', sprite: 'world:house_c', w: 5, h: 2, name: 'Pavillon de chasse' },
    N: { kind: 'note', id: 'n_bois_pavillon', ground: ',' },
    Q: { kind: 'note', id: 'n_bois_braconnier' },
    C: { kind: 'chest', id: 'bois_pavillon', loot: 'bois_lodge', renew: true, name: 'Coffre du pavillon' },
    U: { kind: 'chest', id: 'bois_etang', loot: 'bois_pond', renew: true, sprite: 'world:crate_b', name: 'Panier de cueillette' },
    V: { kind: 'chest', id: 'bois_braconnier', loot: 'bois_poacher', sprite: 'world:crate_stack', name: 'Cache du braconnier' },
    Z: { kind: 'chest', id: 'bois_reserve', loot: 'bois_reserve', renew: true, sprite: 'world:barrels', name: 'Réserve des chasseurs' },
    M: { kind: 'prop', sprite: 'props:cave_mouth', w: 2, h: 1, name: 'Tanière' },
    B: { kind: 'boss', type: 'predator', id: 'bois_predateur', ground: ',' },
    '1': { kind: 'spawn', group: ['rat', 'rat'] },
    '2': { kind: 'spawn', group: ['wolf', 'wolf'] },
    '3': { kind: 'spawn', group: ['wolf'] },
    '4': { kind: 'spawn', group: ['deer', 'deer'] },
    '5': { kind: 'spawn', group: ['rat'] },
  },
  areas: [
    { name: 'Lisière', x: 2, y: 36, w: 14, h: 11, landmark: true },
    { name: 'Pavillon de chasse', x: 22, y: 14, w: 14, h: 12, landmark: true },
    { name: 'Étang aux saules', x: 4, y: 11, w: 14, h: 13, landmark: true },
    { name: 'Cache du braconnier', x: 2, y: 2, w: 7, h: 7, landmark: true },
    { name: 'Tanière du prédateur', x: 48, y: 0, w: 16, h: 15, landmark: true },
    { name: 'Réserve des chasseurs', x: 43, y: 17, w: 9, h: 8, landmark: true },
    { name: 'Éboulis de l’est', x: 52, y: 17, w: 11, h: 16, landmark: true },
    { name: 'Prairie aux cerfs', x: 46, y: 34, w: 15, h: 11, landmark: true },
  ],
  rows: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~~TT###############',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~TTT#####M#########',
    'TTTTTTTTTTTTTTTT.TTT....TTTT.TT.T.TTTTTT.T.T~~..TTTTTTTTTTTTTTT#',
    'TTTT...TTTTT.T......f.T......".T.Tr.*.T....~~~f.T,,,,,,,,,,,,,TT',
    'TTT.V...TTTTTTf...TT....T......T".T.......~~~~~.T,,,,,,,,,,,,,TT',
    'TTT...Q.TTTT........T..............p.T.f.~~~~~~~T,,,,,,,,,,,,,TT',
    'TTT...T.TTTT.Tf"T......."...*.."..fT.....~~~~~~~T,,,,,,,,,,,,,TT',
    'TTTTTT...TTT.T..."."...T............"....~~~~~~~T,,,,,,B,,,,,,TT',
    'TTTTTTT..TTT........."3.......Tf....T...f.~~~~~.T,,,,,,,,,,,,,TT',
    'TTTTTTT...TT.......T.....T......T".........~~~..,,,,,,,,,,,,,,TT',
    'TTTTTTT..TTT."T.....Tf....T......T..."."..~~..T.,,,,,,,,,,,,,,TT',
    'TTTTTTT..TTT.................."......T...~~~...",,,,,,,,,,,,,,TT',
    'TTT..........m...........................~~...,,T,,,,,,,,,,,,,TT',
    'TTT...b..T.fT..p.r....................,.==.,,,,,T,,,,,,,,,,,,,TT',
    'TT.T....T.~~~..b.f...T...."."...*...,,,,,,,,,,.TTTTT,,,TTTTTTTTT',
    'TT.......~~~~~....T...............,,,,,.==.,"...".....T.......TT',
    'TT....hT~~~~~~~.."................,,,...~~T............p......TT',
    'TTT...."~~~~~~~"mf..T......L......,T....~~T"..."....f..T......TT',
    'TT..*m.T~~~~~~~...f*.............C...fT.~~......r.T*.r.....###TT',
    'TT..T....~~~~~......r.....,,,,,,,.T.....~~...2......"r.....###TT',
    'TTT.......~~~..b...Tp.....N,,,,,,.......~~...T...."f......o###TT',
    'TT.T...br.T...h.,,,,,,,,,.,,,,,K,.......~~.....Z"..........###TT',
    'TTTT....Ub.............r,..........p....~~~.T.....p.......c###TT',
    'TT..T..p....T...T.............,...1......~~..T....2....Tro.###TT',
    'TT.T.....T.."T...TTTf.f.....".,....."...T~~........"..RR...###TT',
    'TTT.Tf..."T.............."1.T.,..........~~~.....f.T.....T.###TT',
    'TTT.........5..p........"....f,TT..T.T....~~........*...,To###TT',
    'TTT..*............f.T.....f..",.......T...~~~.....p....,,,.###TT',
    'TT..TT.f..T.T.T....TT..T.....",.........T.r~~.T.......,RRf.###TT',
    'TT........T...T..T.....T......,T.......,...==.,.......,,*o.###TT',
    'TTT.".T...".".3.*...TT.T....f,,,,,,,,,,,,,,,,,,,,,...,,..rc###TT',
    'TTT.......T.T.T*.T.f....".T..,,T...rT.T,TT.==T,,,,,,,,,..r.###TT',
    'TTT."..."..TT.T..............,,...........T~~..T.,,,,,...f*T.TTT',
    'TT.."...TT.....""."f5....T.T.,,............~~.......,....."...TT',
    'TT....T........Tf"T."......f,,,..T.........~~.fr".............TT',
    'TTT.f..........T....p..T.T..,,f...T..T..f.T~~................TTT',
    'TT.......".......f.......p..,,"........T...~~.........f......TTT',
    'TTT....".........T".TT."...r,,."....T.f....~~.......f........TTT',
    'TT............."....."*.,,,,,,..........T.~~~.T..f..4..".....TTT',
    'TT..................,,,,,,,,,".......T..T."~~T......ff.f..."..TT',
    'TTT.......J..T.T,,,,,,,,,.T"........3......~~.......f........TTT',
    'TT...........,,,,,,,,"T...T....T...T..T....~~~T.........4..f..TT',
    'TTT....P.....,,,,......rT."...".T.*...".T.T.~~...............TTT',
    'TTT..............."..p.r..."Tf.........T....~~......"......f..TT',
    'TT..E.............T.T.......T..T..........T.~~~.......f....T.TTT',
    'TTTTTTT..TTTTTTTT.TT....TTT.T.T.TTTT.TTT.T.T.~~.TTT..TT.TTT..TTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~TTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~~TTTTTTTTTTTTTTTT',
  ],
};
