// Carte « bois » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_BOIS: MapDef = {
  id: 'bois',
  name: 'Bois des chasseurs',
  palette: 'summer',
  base: '.',
  wall: 'cliff',
  light: { darkness: 0.0, color: [0, 0, 0] },
  viewTiles: 11.5,
  music: 'music_day',
  trees: ['world:tree_oak_a', 'world:tree_oak_b', 'world:tree_pine_a', 'world:tree_pine_b', 'world:tree_autumn_a'],
  deadTrees: ['world:tree_dead'],
  legend: {
    E: { kind: 'exit' },
    P: { kind: 'start' },
    J: { kind: 'checkpoint', id: 'bois_lisiere', name: 'Halte de la lisière' },
    K: { kind: 'checkpoint', id: 'bois_pavillon', name: 'Feu du pavillon', ground: ',' },
    L: { kind: 'lodge', sprite: 'world:house_c', w: 5, h: 2, name: 'Pavillon de chasse' },
    N: { kind: 'note', id: 'n_bois_pavillon', ground: ',' },
    Q: { kind: 'note', id: 'n_bois_braconnier' },
    C: { kind: 'chest', id: 'bois_pavillon', loot: 'bois_lodge', renew: true, name: 'Coffre du pavillon' },
    U: { kind: 'chest', id: 'bois_etang', loot: 'bois_pond', renew: true, sprite: 'world:crate_b', name: 'Panier de cueillette' },
    V: { kind: 'chest', id: 'bois_braconnier', loot: 'bois_poacher', sprite: 'world:crate_stack', name: 'Cache du braconnier' },
    Z: { kind: 'chest', id: 'bois_reserve', loot: 'bois_reserve', renew: true, sprite: 'world:barrels', name: 'Réserve des chasseurs' },
    M: { kind: 'prop', sprite: 'props:cave_mouth', w: 2, h: 1, name: 'Tanière' },
    B: { kind: 'boss', type: 'predator', id: 'bois_predateur', ground: ',' },
    '1': { kind: 'spawn', group: ['rat', 'rat'] },
    '2': { kind: 'spawn', group: ['wolf', 'wolf'] },
    '3': { kind: 'spawn', group: ['wolf'] },
    '4': { kind: 'spawn', group: ['deer', 'deer'] },
    '5': { kind: 'spawn', group: ['rat'] },
  },
  areas: [
    { name: 'Lisière', x: 2, y: 36, w: 14, h: 11, landmark: true },
    { name: 'Pavillon de chasse', x: 22, y: 14, w: 14, h: 12, landmark: true },
    { name: 'Étang aux saules', x: 4, y: 11, w: 14, h: 13, landmark: true },
    { name: 'Cache du braconnier', x: 2, y: 2, w: 7, h: 7, landmark: true },
    { name: 'Tanière du prédateur', x: 48, y: 0, w: 16, h: 15, landmark: true },
    { name: 'Réserve des chasseurs', x: 43, y: 17, w: 9, h: 8, landmark: true },
    { name: 'Éboulis de l’est', x: 52, y: 17, w: 11, h: 16, landmark: true },
    { name: 'Prairie aux cerfs', x: 46, y: 34, w: 15, h: 11, landmark: true },
  ],
  rows: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~~TT###############',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~TTT#####M#########',
    'TTTTTTTTTTTTTTTT.TTT....TTTT.TT.T.TTTTTT.T.T~~..TTTTTTTTTTTTTTT#',
    'TTTT...TTTTT.T...r....T........TfT."..T....~~~.*T,,,,,,,,,,,,,TT',
    'TTT.V..rTTTTTT...fTT....T..f...T..T.."....~~~~~.T,,,,,,,,,,,,,TT',
    'TTT...Q.TTTT........T................T...~~~~~~~T,,,,,,,,,,,,,TT',
    'TTT...T.TTTT.T..T.f."..p..f."......T"*...~~~~~~~T,,,,,,,,,,,,,TT',
    'TTTTTTT.TTTT..T.f.....".T"...............~~~~~~~T,,,,,,B,,,,,,TT',
    'TTTTTTT"TTTT.T........3....""...T.....T...~~~~~.T,,,,,,,,,,,,,TT',
    'TTTTTTTT.TTTf.......f..T.....T......T....".~~~..,,,,,,,,,,,,,,TT',
    'TTTTTTTT..TT...T..T...".T.....T.....fT....~~...",,,,,,,,,,,,,,TT',
    'TTTTTTTTT.TT"T.T......................"..~~~T...,,,,,,,,,,,,,,TT',
    'TTT......."..m......."...................~~...,,T,,,,,,,,,,,,,TT',
    'TTT...b.h...TT..T.........f.......r.p.,.==.,,,,,T,,,,,,,,,,,,,TT',
    'TT.....T..~~~..b.........T......f.".,,,,,,,,,,".TTTT,,,TTTTTTTTT',
    'TT....T..~~~~~*.......T...........,,,,,.==.,T......."*..".T...TT',
    'TT....h.~~~~~~~..TT...............,,,...~~..".T..........p....TT',
    'TTT.....~~~~~~~.m.....""T..L......,f...T~~....T.f.."..."...T..TT',
    'TT...m..~~~~~~~.f.T....*.........C..f...~~..T........r.Tf..###TT',
    'TT.....*T~~~~~....r.......,,,,,,,.....T.~~.r.2.......r.....###TT',
    'TTT.."....~~~..b.......T..N,,,,,,.......~~....p..T........o###TT',
    'TT."...b...f..h.,,,,,,,,,.,,,,,K,.....".~~.r...Z........"..###TT',
    'TTT....TUb..............,...............~~~"....T..r......c###TT',
    'TT..p...T.......Tp..T........p,...1...T..~~......T2.....ro.###TT',
    'TT...T.T.....T...T...TTT".....,....f."f..~~...T"......RR...###TT',
    'TTT.."..T.....T..."..f....1...,..T.".....~~~...........T...###TT',
    'TTT..T...f..5.................,..".TT..TpT~~......f.....,.o###TT',
    'TTT...T...*.....*.......T.....,...f..."...~~~Tf........,,,.###TT',
    'TT......TT....T.T.T...pTT.fT..,......."....~~.T...T...,RR..###TT',
    'TT.......r....T.f.T..T.....T..,....T...,...==.,.......,,.o.###TT',
    'TTT.......T.."3..."."...TT.T.,,,,,,,,,,,,,,,,,,,,,.*.,,..rc###TT',
    'TTT........f..T.T.T..T.....*.,,.T..T".f,.T.==T,,,,,,,,,TTr.###TT',
    'TTTT........"..TTrT".........,,............~~...T,,,,,..T....TTT',
    'TT...T......TT"*..f.5..""."..,,T.T...f.....~~.......,.........TT',
    'TT......".T........T..T...".,,,"....fT.....~~..f........".....TT',
    'TTTf...r..........fT.......T,,.T......T..T.~~................TTT',
    'TT.....f........."..........,,...f...."....~~T...f.."........TTT',
    'TTT............".....T..TT..,,".."....."T..~~..............f.TTT',
    'TT..................r..",,,,,,....."...*..~~~.......4....f...TTT',
    'TT................f.,,,,,,,,,.f......"...T.~~.T.......f.....".TT',
    'TTT.......J.....,,,,,,,,,*T.T.T.fpf"3......~~..."........ff..TTT',
    'TT...........,,,,,,,,.....T...T".*.T...T..T~~~.f...."...4f....TT',
    'TTT....P.....,,,,...T"......T.....".T.."....~~T............."TTT',
    'TTT....................r..".....T...".....rT~~f....f..........TT',
    'TT..E.................T.T....r..T..T........~~~..T...........TTT',
    'TTTTTTT..TTTTTTTT.TT....TTT.T.T.TTTT.TTT.T.T.~~.TTT..TT.TTT..TTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~TTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT~~~TTTTTTTTTTTTTTTT',
  ],
};
