// Carte « camp » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_CAMP: MapDef = {
  id: 'camp',
  name: 'Le camp',
  palette: 'summer',
  base: '.',
  wall: 'none',
  light: { darkness: 0.12, color: [60, 40, 20] },
  viewTiles: 11,
  music: 'music_camp',
  trees: ['world:tree_oak_a', 'world:tree_oak_b', 'world:tree_pine_a', 'world:tree_pine_b'],
  deadTrees: ['world:tree_dead'],
  legend: {
    H: { kind: 'house' },
    X: { kind: 'door', to: 'house', ground: ',' },
    F: { kind: 'building', type: 'campfire', ground: ',' },
    W: { kind: 'building', type: 'workbench', ground: ',' },
    C: { kind: 'building', type: 'chest' },
    A: { kind: 'rack' },
    D: { kind: 'building', type: 'dummy' },
    S: { kind: 'travel' },
    Y: { kind: 'reserved', name: 'Emplacement réservé (futur compagnon)' },
    P: { kind: 'start' },
  },
  areas: [
    { name: 'Le camp', x: 0, y: 0, w: 40, h: 30 },
  ],
  rows: [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'T..T...................................T',
    'TT.........f......................T..TTT',
    'TTT...............................T...TT',
    'T.....f..........H....................TT',
    'T.T...............................T.T.TT',
    'T......T............................T..T',
    'TT.TT.............X................T..TT',
    'T.T..............,,,............f..T.TTT',
    'T.T...........C...,,.............fT...TT',
    'TT...T...f........,,...........Y....T..T',
    'T...f....Y........,,,,...............TTT',
    'TTT..TT......A....,,,,,.W..........Tf.TT',
    'T................,,,F,,,...............T',
    'TT...T...........,,,,,,,...........TT.TT',
    'TT................,,,,,.............T.TT',
    'T..................,,,....D.......TT..TT',
    'TT.p................P.........f.......TT',
    'TT...T..............,.......f..f.......T',
    'TT..................,...........~~~.ff.T',
    'TT.T................,..........~~~~~f.TT',
    'TT....T.......f.....,..........~~~~~.fTT',
    'T.T.f.........p..p..,..........~~~~~...T',
    'TT...T........f....,,,.f........~~~....T',
    'TT..p...............,..............f..TT',
    'T....f......f.......,.S............f.f.T',
    'TT...T..............,..................T',
    'TTT.TTTTTT.TT.TT.TT.,TT..T...TTT.T.T.TTT',
    'TTTTTTTTTTTTTTTTTTT,,,TTTTTTTTTTTTTTTTTT',
  ],
};
