// Carte « carriere » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_CARRIERE: MapDef = {
  id: 'carriere',
  name: 'Ancienne carrière',
  palette: 'summer',
  base: ',',
  wall: 'cliff',
  light: { darkness: 0.28, color: [30, 20, 10], caveDarkness: 0.5 },
  viewTiles: 12,
  music: 'music_ruins',
  trees: ['world:tree_dead', 'props:tree_bare_a'],
  deadTrees: ['world:tree_dead'],
  legend: {
    E: { kind: 'exit', only: 'main' },
    P: { kind: 'start', only: 'main' },
    '@': { kind: 'start', only: 'dungeon' },
    '&': { kind: 'exit', only: 'dungeon' },
    J: { kind: 'checkpoint', id: 'carriere_crete', name: 'Halte de la crête', only: 'main' },
    Q: { kind: 'checkpoint', id: 'carriere_camp', name: 'Feu des carriers', only: 'main' },
    K: { kind: 'checkpoint', id: 'carriere_galeries', name: 'Lanterne des galeries' },
    Y: { kind: 'shortcut', id: 'carriere_echelle', name: 'Échelle relevée', sprite: 'props:ladder', from: 'south', cells: { dx: 0, dy: 0, w: 1, h: 2 } },
    M: { kind: 'prop', sprite: 'props:cave_mouth', w: 2, h: 1, name: 'Entrée des galeries' },
    W: { kind: 'prop', sprite: 'props:table_rough', w: 2, h: 1, solid: true, name: 'Table des carriers' },
    O: { kind: 'prop', sprite: 'world:barrels', w: 2, h: 1, solid: true },
    A: { kind: 'prop', sprite: 'props:rock_tower_s', w: 2, h: 1, solid: true, occluder: true, name: 'Tour de pierres' },
    N: { kind: 'note', id: 'n_carriere_camp' },
    I: { kind: 'prop', sprite: 'props:stalagmite_s', w: 1, h: 1, solid: true },
    C: { kind: 'chest', id: 'carriere_filons', loot: 'carriere_common', name: 'Caisse des filons', sprite: 'world:crate_stack', only: 'main' },
    U: { kind: 'chest', id: 'carriere_fond', loot: 'carriere_common', name: 'Caisse du fond', sprite: 'world:crate_b', only: 'main' },
    V: { kind: 'chest', id: 'carriere_recoin', loot: 'carriere_rare', name: 'Coffre du recoin', only: 'main' },
    Z: { kind: 'chest', id: 'carriere_tresor', loot: 'carriere_boss', sprite: 'world:chest_big_closed', name: 'Nid du ver' },
    B: { kind: 'boss', type: 'worm', id: 'carriere_ver' },
    '1': { kind: 'spawn', group: ['fox_c', 'fox_c'], slot: 'a' },
    '2': { kind: 'spawn', group: ['husk'], asleep: true, slot: 'a' },
    '3': { kind: 'spawn', group: ['bear_c'], slot: 'b' },
    '4': { kind: 'spawn', group: ['wraith'], slot: 'c' },
    '5': { kind: 'spawn', group: ['rat', 'rat'], slot: 'a' },
  },
  areas: [
    { name: 'Crête', x: 1, y: 1, w: 62, h: 12, landmark: true },
    { name: 'Terrasse des carriers', x: 18, y: 15, w: 26, h: 13, landmark: true },
    { name: 'Filons de l’est', x: 48, y: 15, w: 15, h: 13, landmark: true },
    { name: 'Fond de la carrière', x: 1, y: 30, w: 62, h: 8, landmark: true },
    { name: 'Galeries', x: 1, y: 38, w: 62, h: 14, cave: true, landmark: true },
    { name: 'Grande caverne', x: 20, y: 43, w: 26, h: 9, cave: true },
  ],
  rows: [
    '################################################################',
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#',
    '#,,,ttt,t,,tt,,t,,,,,,t,,t,,,,,tp,,tt,,t,,,,tt,,ttt,t,,,,"t,,,,#',
    '#,,Etttt,,t,ttt,,,t,tpt"",,,t,tt,tt,,,,,t,tt,,tt,tp,t",ttt,t,,,#',
    '#,,,,P,,,,,,,,,,r,,,,,,",r,,,,,,,tt,,,,",,,,,p,,,,,,,,,,p,,",,,#',
    '#,p,,,",J,,,,,,,,,,,,,,,,p,,r,,,,,,,,,,,,,,,tt,",,,,,,,,,,,,,,,#',
    '#,,r,",,,,,,,"tt,,r,,,,,r,,,,,,,,,,,,,5,",,,,,,,,r,,,",,,,,,,,,#',
    '#,,,p",,,,,,,",,,,,,1,,,,,,,p,r,,,,,,,,,p"p",,,,,,,",,,,,,,,tt,#',
    '#,,,,p,,,r,",r,,,,,,r,p,,,,pp,,,,,,,,,,,,,,,,,,,",,",,pr""",,,,#',
    '#,p,,,,,,,,",,,,,,,",,p,,,tt,,"r,,,p",,,1,,,r,,,r,,,tt,,,,,,,,,#',
    '#,,,r,,,,p,r",r,,,,,,,,,pp,,,",,,,",,,,,,,,,,,,,,,,,,p,p,p,r,,,#',
    '#,,,,,,,p,,,,",,,,r,,"",,,,,,,,,,,,,,,,,,,,,,,,",,,",,,,,,,,,r,#',
    '#,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,#',
    '#####Y############################################,,,###########',
    '##################################################,,,###########',
    '#,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#',
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,r,,,,,,,,,,RR,p,,,,,#',
    '#,,,,,,,,,,,p,,,,,RR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,o,,,#',
    '#,,,,,,,RR,,,,,,,,,,,,,,,W,,,,,,,O,,,,W,,,,r,,,,p,,,,,r,o,,,,,,#',
    '#,,,,,r,,,,,,,,,r,,,,r,,,,,,,N,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,#',
    '#,,,,,,,,r,,,,,,,,,,,,A,,,,,,,,,,,,,,,,,,,,,,,2,,,,,,,,,,cr,,,,#',
    '#,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,Q,,,,,,,,,,p,,,p,,,,,,,,,,,o,,,,#',
    '#,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,r,5,,,,,,#',
    '#,,,r,,,,,,,r,,,,p2,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,#',
    '#,,,,,,,,,,,RR,,,,,,,,,,,,,O,,,,,,,,O,,,,,,,p,,,,,,,,,,o,,p,c,,#',
    '#,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,RR,p,,,,,,,,,,,p,#',
    '#,,r,t,,t,,,,,,,t,,ttt,,,,,pp,,,p,t,,,t,,,,,,,,,,,,,t,,t,,,tCp,#',
    '#,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,p,,,,,,,,,,,p,,,,,,,,#',
    '########,,,#####################################################',
    '########,,,#####################################################',
    '#,,,,,,,,,,,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,#',
    '#,,,,r,,r,,,3,,,,,,r,,,r,,,s,,,,,,,,RR,,,,,,,,,o,,,,,,,,,,,,r,,#',
    '#,r,,,,,,,,p,,p,,,,,,,RR,,,,,,,,,,,,,,,,,,r,,,,,,,,,,,,,,,,,,,,#',
    '#,,,,p,sr,,,,,o,,,p,sr,,,,,,,p3,,,r,,,r,,,,s,,,,,,,,c,,,,,sp,,,#',
    '#,,r,p,,,,,,,,,,,,,,,,,,r,,r,,,,p,,,,,,,o,,,,,p,3,,,,,,,,sp,,,,#',
    '#,,,,,U,,r,,,p,,r,,,c,,,,,,,,s,,,,,,,,,,,,,sRR,,,,,r,,,p,,,,,,,#',
    '#,p,r,,r,,,,,,,,,,,p,,,,,,,RR,p,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,,,#',
    '#,,,,,,,,,,,,,,,,,,,s,,,,,,,,,,,,,,,p,,,,,p,,p,,p,,,,,,,p,,,p,,#',
    '############################,,,,,,,,,###########################',
    '###########################,,,,M,,,,,,##########################',
    '##########################,,,,,,,,,,,,,#########################',
    '##############,,,,,,,,p,,,,,,&,,,,s,,,www,,p,,,,,,,,,,p,,,,x####',
    '##############,,,,,,,,,,I,,,,,@,,K,,,,,,,,,I,,,,,,xx,,,,,,V,####',
    '##############,I,,,,,,,,,,,,,,s,,,,,,,,,,,,,,,,,p,,,s,x,,,,,####',
    '####,,p,,,,,p,p,,,,,,,,,p,,,,,,,,,,,,,,,,p,,4,,I,,,,,,,,,,,,####',
    '####,,,,,,x,,,p,,,,,,,4,,,,,,,,,x,,w,p,,,,,,,,,,,,,,,w,,,,,,####',
    '####,,,,,p,,,,,,,,I,,,wp,,,,,,,,B,,,,,,p,,,,,p,,,,##############',
    '####p,wxZ,,,,,,,p,,,,,,,,p,w,,,,,,p,,,,p,,,,,,,,,,##############',
    '####,,,,,,4,,,,,,,,,x,,,,,,,s,xs,,,x,,w,Iss,,,,,,w##############',
    '####,,,,,,,,,,,,,,,,,,,,,,,,,p,,,,,,,,,,,,,,x,p,x,##############',
    '########################,,,,,,,,,,,,,,,,,#######################',
    '#########################,,,,,,,,,,,,,,,########################',
  ],
};
