// Carte « marais » — dessinée en ASCII (légende : src/maps/types.ts ; brouillon : tools/maps/draw_maps.py).
import type { MapDef } from './types';

export const MAP_MARAIS: MapDef = {
  id: 'marais',
  name: 'Marais corrompu',
  palette: 'autumn',
  base: '.',
  wall: 'none',
  light: { darkness: 0.62, color: [10, 22, 30] },
  viewTiles: 11.5,
  music: 'music_eerie',
  trees: ['props:tree_twisted', 'props:tree_bare_c', 'props:tree_bare_d', 'world:tree_dead'],
  deadTrees: ['props:tree_bare_a', 'props:tree_bare_b', 'world:tree_dead'],
  legend: {
    E: { kind: 'exit' },
    P: { kind: 'start' },
    J: { kind: 'checkpoint', id: 'marais_passerelle', name: 'Lanterne de la passerelle', votive: true },
    V: { kind: 'checkpoint', id: 'marais_ilot', name: 'Lanterne de l’îlot', votive: true },
    L: { kind: 'lodge', sprite: 'world:house_c', w: 5, h: 2, name: 'Cabane de la guérisseuse' },
    N: { kind: 'note', id: 'n_marais_cabane' },
    O: { kind: 'prop', sprite: 'props:dolmen_d', w: 4, h: 1, solid: true, occluder: true, name: 'Dolmen' },
    I: { kind: 'prop', sprite: 'props:menhir_d', w: 1, h: 1, solid: true, name: 'Menhir' },
    G: { kind: 'prop', sprite: 'props:tree_giant_dead', w: 3, h: 1, solid: true, occluder: true, name: 'Arbre-mort' },
    Z: { kind: 'chest', id: 'marais_chapelle', loot: 'marais_rare', renew: true, sprite: 'world:chest_big_closed', name: 'Coffre de la chapelle' },
    U: { kind: 'chest', id: 'marais_arbre', loot: 'marais_common', renew: true, sprite: 'world:crate_b', name: 'Offrandes de l’arbre-mort' },
    Q: { kind: 'chest', id: 'marais_roseliere', loot: 'marais_hidden', sprite: 'world:crate_stack', name: 'Cache de la roselière' },
    Y: { kind: 'shortcut', id: 'marais_tronc', name: 'Tronc couché', sprite: 'props:bridge_deck', from: 'north', cells: { dx: 0, dy: 1, w: 2, h: 7 } },
    F: { kind: 'spawn', group: ['flower'] },
    '1': { kind: 'spawn', group: ['husk'], asleep: true },
    '2': { kind: 'spawn', group: ['fox_c', 'fox_c'] },
    '3': { kind: 'spawn', group: ['wraith'] },
    '4': { kind: 'spawn', group: ['rat', 'rat'] },
  },
  areas: [
    { name: 'Passerelle', x: 26, y: 38, w: 12, h: 10, landmark: true },
    { name: 'Îlot de la guérisseuse', x: 25, y: 17, w: 14, h: 13, landmark: true },
    { name: 'Roselière', x: 2, y: 7, w: 15, h: 27, landmark: true },
    { name: 'Chapelle engloutie', x: 45, y: 9, w: 15, h: 13, landmark: true },
    { name: 'Arbre-mort', x: 26, y: 2, w: 10, h: 10, landmark: true },
  ],
  rows: [
    'tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt',
    'tttttttt~t~ttttt~tt~tttt~tttt~~tt~~t~~tt~~tttttttt~~~~~ttttttt~t',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~j~~~~~~~~~~~~~~~~tt',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~~~~tj.~~~~~~~~~~~~~~~~~~~~~~~~~~~~~tt',
    't~~~~~~~~~~~~j~~~~~~~~~~~~~~~..t.t~~~~~~~j~~~~~~~j~~~~~~~~~~~~tt',
    't~~~~~~~~~~~~~~~~~j~~~~~~~~~....t..~~~~~~...~~~~~~~~~~~~~~~~~~tt',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~........t~~~~j.t.~~~~~~~~~~~~~~~~~~~t',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~.t.G....jj~~~~...~~~~~~~~~~~~~~~~~~~t',
    'tt~.t.g.........~~~~~~~~~~~.....j...~~~~~~~~~~~~~~~~~~~~~~~~~jtt',
    'tt~.~~j~~.h...gg~~~~~~~~~~~~.....U.~~~~~~~~~~~~~~~~~~~~~~~~~~~~t',
    'tt~...tt..~~~~..~~~~~~~~~~~~~..,t.~~~~~~~j~~~~~j~~~...~~~~~~~~tt',
    'tt~j..j...j....j~~~~.~~~~~~~~~,,,~~~~~~~~~~~~~~~~.O..t..~~~~~~~t',
    't~~g.k.2....j...~~~.t.~~~~~~~~~,,~~~~~~~~~~~~~~~:::::::::~~~~~tt',
    'tt~g.~~~~..jgt..~~~~.~~~~~~~~~~,,~~~~~~~~~~~~~~I:::::::::I~~~~~t',
    'tt~.gt..kt~~~~t.~~~~~~~~~~~~~j1,,~~~~~~~~~~~~~~.:::::::3:.~~~~tt',
    'tt~...jt..j...tk~~~~~~~~~~~~~~~,,~~~~~~~~~~~~~..:::::::::k.~~~tt',
    'tt~....t.....t..~~~~~~~~~~~~~j~,,,,,~~~~~~~~~~..::::Z::::..~~~tt',
    'tt~...~~~h......~~~~~~~~~~~~~~~,,,,,~~~~~~~~~~,t:::::::::..~~~~t',
    'tt~.....k.~~~~..~~~~~~~~~~~~~~~,,,,,~~j~~~~====,::3::::::.~~~~~t',
    't~~..t..t.tt..jj~~~~~~~~~~~j.L.......~~~=======I:::::::::I~~~~tt',
    't~~......t.j1jj.~~~~~~~~j~~~.........===F===~~~~.t.....j.j~~~~~t',
    'tt~.~~~~~...t.j.~~~~~~~~j~~..........,===~~~~~~~~.......~~~~~~tt',
    'tt~.jt....~~j~g.~~~~~~j~~~~..........,~~~~~~~~~~~~~.j.~~~~~~~~tt',
    'tt~.....tt......~~~~~~~~~~............j~~~~~~~~~~~~~~~~~~~~j~~tt',
    'tt~...j......t.j,,,F,1,,,,,............~~~~~~~j~~~~~~~~~j~~~~~~t',
    'tt~..~~~~..j....~~~~~~~~~~t.N..........~~~~~~~~~~~~~~~~~~~~~~~tt',
    'tt~.t.....~~~~..~~~~~~~~~~~........V..~~~~~~~~~~~~~~~~~~~~~~~~tt',
    't~~.k...j..2.k..~~~~~~~~~~~...........~~~~~~~~~~~~~~~~~~~~~~~~tt',
    'tt~t.t.j.t.k....~~~~~~~~~~~~.........j~~~~~~~~~j~~.~~~~j~~~~~~tt',
    'tt~.Qt~~~.......~~~~~~~~~t..~..,,,..~~~~~~~~~~~~~...~~~~~~~~~~tt',
    't~~.......~j~~g.~~~~~~~~Y.t.~~~,,.4~~~~~~~~~~~~~..t..~~~~~~~~~tt',
    'tt~...........j.~~~~~j~~~~~~~~~,,~~~~~~~~~j~~~~~~...~~~~~~~~~~~t',
    'tt~t............~~~~~~~~~~~~~~,,~~~~~~~~~~~j~~~~~~.~~~~~~~~~~~~t',
    'tt~~~~~~~~j~~~~~~~~~~~~~~~~~~~,,~~~~~~~~~~~~~~~~~j~~~~~~~~~~~~tt',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~~~,,,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~t',
    't~~~j~~~~~~~~~~~~~~~~~j~~~~~~~,,~~~~~~~~~~~...~~~~~~~~~~~...~~~t',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~~~~,1~~j~~~~~~~~.t.~~~~~~~~~~~.t.~~tt',
    'tt~~~~~~~~~~~~~~~~~~~~~~~~~~~~,,,~~j~~~~~~~...~~~~~~~~~~~...~~~t',
    'tt~~~~~~~~~~~~~~~~~~~~.th..~~~~,,~~~~~~~~~~~~~~~~~~~~~~j~~~j~~tt',
    'tt~~~~~~~~~~~...~~~~~~.....~~~~,,~~~~~~~~~~~j~~~~~~~~~~~~~~~~~tt',
    'tt~~~~~~~~~~~.t.~~~~~~..h,t~j~~,,,~~~j~~~~~~~~j~~~~j~~~~~~~~~~tt',
    't~~~~~~~~~~~~...~~~~~~j~~~,,~~..,..~~~~~~~~~j~~~~~~~~~~~~~~~~~tt',
    'tt~~~~~~~~~~~~~~~~~~~~~~j~~,,..t..J.~~~~~~~~~~~~~~~~~~~~~~~~~~~t',
    't~~~~~~~~~~j~~~~~~~~~~~~~~~~,,..P..j.~~~~~~~~~~~~~~~~~~~~~~j~~~t',
    'tt~~j~~~~~~~~~~~~~~~~~~~~~~~.t...tj..~~~~~~~~~~~~~~~~~~~~~~~~~tt',
    't~~~~~~~~~~~~~~~~~~j~~~~~~j~.........~~~~~~~~~~~~~~~~~~~~~~~~~tt',
    'tt~tt~tttttt~ttttt~ttttttttt~.E==...~ttttttt~tt~tttttt~t~t~tt~~t',
    'tttttttttttttttttttttttttttttt.==..ttttttttttttttttttttttttttttt',
  ],
};
